package com.linky.heaven.dao.orm;

import com.linky.heaven.dao.orm.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "movie".
 */
public class MovieBean {

    private Long id;
    private Integer type;
    /** Not-null value. */
    private String name;
    private java.util.Date date;
    private String parse_page_url;
    private String download_ftp;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MovieBeanDao myDao;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MovieBean() {
    }

    public MovieBean(Long id) {
        this.id = id;
    }

    public MovieBean(Long id, Integer type, String name, java.util.Date date, String parse_page_url, String download_ftp) {
        this.id = id;
        this.type = type;
        this.name = name;
        this.date = date;
        this.parse_page_url = parse_page_url;
        this.download_ftp = download_ftp;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMovieBeanDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getParse_page_url() {
        return parse_page_url;
    }

    public void setParse_page_url(String parse_page_url) {
        this.parse_page_url = parse_page_url;
    }

    public String getDownload_ftp() {
        return download_ftp;
    }

    public void setDownload_ftp(String download_ftp) {
        this.download_ftp = download_ftp;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
