package com.linky.heaven.dao.orm;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.linky.heaven.dao.orm.MovieBean;

import com.linky.heaven.dao.orm.MovieBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieBeanDaoConfig;

    private final MovieBeanDao movieBeanDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieBeanDaoConfig = daoConfigMap.get(MovieBeanDao.class).clone();
        movieBeanDaoConfig.initIdentityScope(type);

        movieBeanDao = new MovieBeanDao(movieBeanDaoConfig, this);

        registerDao(MovieBean.class, movieBeanDao);
    }
    
    public void clear() {
        movieBeanDaoConfig.getIdentityScope().clear();
    }

    public MovieBeanDao getMovieBeanDao() {
        return movieBeanDao;
    }

}
